export const ADD_PROJECT = 'ADD_PROJECT';
export type ADD_PROJECT = typeof ADD_PROJECT;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
